// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package events

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Event() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a class=\"px-4 py-2 bg-gray-200 rounded-md\" href=\"/\">Back</a><h1 class=\"text-5xl font-bold text-center\">Event 1</h1><br><div class=\"mx-12 bg-gray-200 h-44 rounded-xl px-4 py-2\">Meet John Doe at Cafe in London Tomorrow at 13:00?<br>(picture of generic cafe?)</div><br><div class=\"container mx-auto grid grid-cols-1 md:grid-cols-2 gap-4 items-start\"><div class=\"flex flex-col items-center order-2 md:order-1\"><p>You will need to pay £100</p><a href=\"./waiting-room.html\" class=\"bg-gray-200 w-fit px-4 py-2 rounded-md\">Reserve and Pay</a></div><div class=\"px-4 py-2 order-1 md:order-2\">A celeb-provided description from the celebrity about what to expect from this event.<br>e.g. meet me and you will expect to join me for a lovely coffee break at one of my favourite coffee spots in London.</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
